"""Complete trusted health profile and report production contracts.

Revision ID: 0024_health_profile_report
Revises: 0023_trusted_medication_loop
Create Date: 2026-07-15

This migration is expand-only. Existing tables receive only one nullable
medication-purpose column, provably redundant tenant unique constraints, and
non-unique history indexes. All new trust semantics live in new tables, so the
0023 application can continue its existing CRUD paths unchanged.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from app.db.compat import JSONB


revision = "0024_health_profile_report"
down_revision = "0023_trusted_medication_loop"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "trusted_medication_plans",
        sa.Column("purpose", sa.String(length=256), nullable=True),
    )
    op.create_unique_constraint(
        "uq_user_indicator_value_id_user",
        "user_indicator_values",
        ["id", "user_id"],
    )
    op.create_unique_constraint(
        "uq_profile_source_tenant_id",
        "health_profile_sources",
        ["id", "user_id", "subject_user_id"],
    )
    op.create_unique_constraint(
        "uq_score_snapshot_workflow_tenant_id",
        "health_score_snapshots",
        ["id", "source_report_workflow_id", "user_id", "subject_user_id"],
    )
    op.create_index(
        "ix_profile_revision_fact_history",
        "health_profile_revisions",
        ["user_id", "subject_user_id", "fact_id", "target_version", "id"],
    )
    op.create_index(
        "ix_profile_revision_candidate_history",
        "health_profile_revisions",
        ["user_id", "subject_user_id", "candidate_id", "target_version", "id"],
    )

    op.create_table('trusted_device_profile_observations',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('user_indicator_value_id', sa.Integer(), nullable=False),
        sa.Column('idempotency_key', sa.String(length=96), nullable=False),
        sa.Column('source_content_hash', sa.String(length=64), nullable=False),
        sa.Column('metric_mapping_version', sa.String(length=80), nullable=False),
        sa.Column('fact_key', sa.String(length=128), nullable=False),
        sa.Column('value_numeric', sa.Numeric(24, 8), nullable=True),
        sa.Column('value_text', sa.Text(), nullable=True),
        sa.Column('unit', sa.String(length=64), nullable=True),
        sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('source_snapshot', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('status', sa.String(length=16), nullable=False, server_default='active'),
        sa.Column('active_slot', sa.Integer(), nullable=True, server_default='1'),
        sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint('value_numeric IS NOT NULL AND value_text IS NULL', name='ck_device_profile_observation_has_value'),
        sa.CheckConstraint('user_id = subject_user_id', name='ck_device_profile_observation_self_subject'),
        sa.CheckConstraint("fact_key IN ('basic.height', 'basic.weight')", name='ck_device_profile_observation_fact_key'),
        sa.CheckConstraint("metric_mapping_version = 'device-profile.height-weight.v1'", name='ck_device_profile_observation_mapping_version'),
        sa.CheckConstraint("(fact_key = 'basic.height' AND unit = 'cm' AND value_numeric >= 30 AND value_numeric <= 300) OR (fact_key = 'basic.weight' AND unit = 'kg' AND value_numeric >= 1 AND value_numeric <= 500)", name='ck_device_profile_observation_value_domain'),
        sa.CheckConstraint("status IN ('active', 'superseded', 'retracted')", name='ck_device_profile_observation_status'),
        sa.CheckConstraint("(status = 'active' AND active_slot = 1) OR (status IN ('superseded', 'retracted') AND active_slot IS NULL)", name='ck_device_profile_observation_active_slot'),
        sa.CheckConstraint('version >= 1', name='ck_device_profile_observation_version'),
        sa.ForeignKeyConstraint(['subject_user_id'], ['user_account.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_indicator_value_id', 'user_id'], ['user_indicator_values.id', 'user_indicator_values.user_id'], name='fk_device_profile_observation_indicator_owner', ondelete='RESTRICT'),
        sa.UniqueConstraint('user_id', 'subject_user_id', 'user_indicator_value_id', 'version', name='uq_device_profile_observation_source_version'),
        sa.UniqueConstraint('user_id', 'subject_user_id', 'user_indicator_value_id', 'active_slot', name='uq_device_profile_observation_active_source'),
        sa.UniqueConstraint('id', 'user_id', 'subject_user_id', name='uq_device_profile_observation_tenant_id'),
        sa.UniqueConstraint('user_id', 'subject_user_id', 'idempotency_key', name='uq_device_profile_observation_tenant_idempotency'),
    )
    op.create_index('ix_device_profile_observation_subject_fact_time', 'trusted_device_profile_observations', ['user_id', 'subject_user_id', 'fact_key', 'effective_at'], unique=False)
    op.create_table('health_profile_fact_source_versions',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('fact_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('fact_version', sa.Integer(), nullable=False),
        sa.Column('profile_source_id', sa.Integer(), nullable=False),
        sa.Column('source_type', sa.String(length=32), nullable=False),
        sa.Column('source_identity', sa.String(length=192), nullable=False),
        sa.Column('source_snapshot', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint('fact_version >= 1', name='ck_profile_fact_source_version_positive'),
        sa.ForeignKeyConstraint(['fact_id', 'user_id', 'subject_user_id'], ['health_profile_facts.id', 'health_profile_facts.user_id', 'health_profile_facts.subject_user_id'], name='fk_profile_fact_source_version_fact_tenant', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['profile_source_id', 'user_id', 'subject_user_id'], ['health_profile_sources.id', 'health_profile_sources.user_id', 'health_profile_sources.subject_user_id'], name='fk_profile_fact_source_version_source_tenant', ondelete='RESTRICT'),
        sa.UniqueConstraint('fact_id', 'user_id', 'subject_user_id', 'fact_version', 'source_identity', name='uq_profile_fact_source_version_identity'),
    )
    op.create_index('ix_profile_fact_source_version_current', 'health_profile_fact_source_versions', ['user_id', 'subject_user_id', 'fact_id', 'fact_version'], unique=False)
    op.create_table('health_profile_device_source_links',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('profile_source_id', sa.Integer(), nullable=False),
        sa.Column('device_observation_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['device_observation_id', 'user_id', 'subject_user_id'], ['trusted_device_profile_observations.id', 'trusted_device_profile_observations.user_id', 'trusted_device_profile_observations.subject_user_id'], name='fk_profile_device_source_link_observation_tenant', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['profile_source_id', 'user_id', 'subject_user_id'], ['health_profile_sources.id', 'health_profile_sources.user_id', 'health_profile_sources.subject_user_id'], name='fk_profile_device_source_link_source_tenant', ondelete='CASCADE'),
        sa.UniqueConstraint('device_observation_id', 'profile_source_id', 'user_id', 'subject_user_id', name='uq_profile_device_source_link_pair'),
        sa.UniqueConstraint('profile_source_id', 'user_id', 'subject_user_id', name='uq_profile_device_source_link_source'),
    )
    op.create_table('health_profile_goals',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('creation_client_event_id', sa.String(length=80), nullable=False),
        sa.Column('name', sa.String(length=160), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False, server_default='active'),
        sa.Column('started_on', sa.Date(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('confirmed_by_user_id', sa.BigInteger(), nullable=False),
        sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint('length(name) > 0', name='ck_profile_goal_name_nonempty'),
        sa.CheckConstraint("status IN ('active', 'paused', 'completed', 'archived')", name='ck_profile_goal_status'),
        sa.CheckConstraint('version >= 1', name='ck_profile_goal_version'),
        sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['user_account.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['subject_user_id'], ['user_account.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('user_id', 'subject_user_id', 'creation_client_event_id', name='uq_profile_goal_tenant_creation_event'),
        sa.UniqueConstraint('id', 'user_id', 'subject_user_id', name='uq_profile_goal_tenant_id'),
    )
    op.create_index('ix_profile_goal_subject_status', 'health_profile_goals', ['user_id', 'subject_user_id', 'status', 'started_on'], unique=False)
    op.create_table('health_profile_goal_metrics',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('goal_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('metric_key', sa.String(length=128), nullable=False),
        sa.Column('display_label', sa.String(length=160), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint('length(metric_key) > 0', name='ck_profile_goal_metric_nonempty'),
        sa.ForeignKeyConstraint(['goal_id', 'user_id', 'subject_user_id'], ['health_profile_goals.id', 'health_profile_goals.user_id', 'health_profile_goals.subject_user_id'], name='fk_profile_goal_metric_goal_tenant', ondelete='CASCADE'),
        sa.UniqueConstraint('goal_id', 'user_id', 'subject_user_id', 'metric_key', name='uq_profile_goal_metric_key'),
    )
    op.create_table('health_profile_goal_revisions',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('goal_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('actor_user_id', sa.BigInteger(), nullable=False),
        sa.Column('client_event_id', sa.String(length=80), nullable=False),
        sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
        sa.Column('event_type', sa.String(length=24), nullable=False),
        sa.Column('target_version', sa.Integer(), nullable=False),
        sa.Column('before_data', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('after_data', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("event_type IN ('create', 'update', 'status_change', 'archive')", name='ck_profile_goal_revision_event_type'),
        sa.CheckConstraint('target_version >= 1', name='ck_profile_goal_revision_version'),
        sa.ForeignKeyConstraint(['actor_user_id'], ['user_account.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['goal_id', 'user_id', 'subject_user_id'], ['health_profile_goals.id', 'health_profile_goals.user_id', 'health_profile_goals.subject_user_id'], name='fk_profile_goal_revision_goal_tenant', ondelete='RESTRICT'),
        sa.UniqueConstraint('goal_id', 'user_id', 'subject_user_id', 'target_version', name='uq_profile_goal_revision_target_version'),
        sa.UniqueConstraint('user_id', 'subject_user_id', 'client_event_id', name='uq_profile_goal_revision_tenant_event'),
    )
    op.create_index('ix_profile_goal_revision_history', 'health_profile_goal_revisions', ['user_id', 'subject_user_id', 'goal_id', 'target_version', 'id'], unique=False)
    op.create_table('health_report_asset_sets',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('client_request_id', sa.String(length=80), nullable=False),
        sa.Column('media_kind', sa.String(length=24), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False, server_default='open'),
        sa.Column('expected_page_count', sa.Integer(), nullable=True),
        sa.Column('received_asset_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('completeness_basis', sa.String(length=32), nullable=True),
        sa.Column('aggregate_sha256', sa.String(length=64), nullable=True),
        sa.Column('original_summary', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("completeness_basis IS NULL OR completeness_basis IN ('user_declared', 'pdf_page_count', 'ocr_page_numbers', 'legacy')", name='ck_report_asset_set_completeness_basis'),
        sa.CheckConstraint('expected_page_count IS NULL OR expected_page_count >= 1', name='ck_report_asset_set_expected_pages'),
        sa.CheckConstraint("media_kind IN ('camera', 'photo_library', 'pdf', 'csv', 'legacy')", name='ck_report_asset_set_media_kind'),
        sa.CheckConstraint('received_asset_count >= 0', name='ck_report_asset_set_received_assets'),
        sa.CheckConstraint("status = 'open' OR expected_page_count IS NOT NULL", name='ck_report_asset_set_sealed_expected_pages'),
        sa.CheckConstraint("status IN ('open', 'sealed', 'attached', 'rejected', 'retracted')", name='ck_report_asset_set_status'),
        sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['subject_user_id'], ['user_account.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('id', 'user_id', 'subject_user_id', name='uq_report_asset_set_tenant_id'),
        sa.UniqueConstraint('user_id', 'subject_user_id', 'client_request_id', name='uq_report_asset_set_tenant_request'),
    )
    op.create_index('ix_report_asset_set_aggregate_digest', 'health_report_asset_sets', ['user_id', 'subject_user_id', 'aggregate_sha256'], unique=False)
    op.create_table('health_report_assets',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('asset_set_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('asset_index', sa.Integer(), nullable=False),
        sa.Column('client_asset_id', sa.String(length=80), nullable=False),
        sa.Column('original_filename', sa.String(length=256), nullable=False),
        sa.Column('mime_type', sa.String(length=128), nullable=False),
        sa.Column('byte_size', sa.BigInteger(), nullable=False),
        sa.Column('byte_sha256', sa.String(length=64), nullable=False),
        sa.Column('storage_key', sa.Text(), nullable=False),
        sa.Column('width_px', sa.Integer(), nullable=True),
        sa.Column('height_px', sa.Integer(), nullable=True),
        sa.Column('ingest_status', sa.String(length=16), nullable=False, server_default='uploaded'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint('byte_size >= 0', name='ck_report_asset_byte_size'),
        sa.CheckConstraint('asset_index >= 1', name='ck_report_asset_index'),
        sa.CheckConstraint("ingest_status IN ('uploaded', 'accepted', 'rejected')", name='ck_report_asset_ingest_status'),
        sa.ForeignKeyConstraint(['asset_set_id', 'user_id', 'subject_user_id'], ['health_report_asset_sets.id', 'health_report_asset_sets.user_id', 'health_report_asset_sets.subject_user_id'], name='fk_report_asset_set_tenant', ondelete='CASCADE'),
        sa.UniqueConstraint('asset_set_id', 'user_id', 'subject_user_id', 'client_asset_id', name='uq_report_asset_set_client_asset'),
        sa.UniqueConstraint('asset_set_id', 'user_id', 'subject_user_id', 'asset_index', name='uq_report_asset_set_page'),
        sa.UniqueConstraint('id', 'asset_set_id', 'user_id', 'subject_user_id', name='uq_report_asset_set_asset_tenant_id'),
        sa.UniqueConstraint('id', 'user_id', 'subject_user_id', name='uq_report_asset_tenant_id'),
    )
    op.create_index('ix_report_asset_set_order', 'health_report_assets', ['user_id', 'subject_user_id', 'asset_set_id', 'asset_index'], unique=False)
    op.create_table('health_report_asset_set_workflow_links',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('asset_set_id', sa.Integer(), nullable=False),
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['asset_set_id', 'user_id', 'subject_user_id'], ['health_report_asset_sets.id', 'health_report_asset_sets.user_id', 'health_report_asset_sets.subject_user_id'], name='fk_report_asset_set_link_set_tenant', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['workflow_id', 'user_id', 'subject_user_id'], ['health_report_workflows.id', 'health_report_workflows.user_id', 'health_report_workflows.subject_user_id'], name='fk_report_asset_set_link_workflow_tenant', ondelete='CASCADE'),
        sa.UniqueConstraint('asset_set_id', 'workflow_id', 'user_id', 'subject_user_id', name='uq_report_asset_set_link_pair'),
        sa.UniqueConstraint('asset_set_id', 'user_id', 'subject_user_id', name='uq_report_asset_set_link_set'),
        sa.UniqueConstraint('workflow_id', 'user_id', 'subject_user_id', name='uq_report_asset_set_link_workflow'),
    )
    op.create_table('health_report_pages',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('asset_set_id', sa.Integer(), nullable=False),
        sa.Column('source_asset_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('page_index', sa.Integer(), nullable=False),
        sa.Column('source_page_index', sa.Integer(), nullable=False),
        sa.Column('rendered_byte_sha256', sa.String(length=64), nullable=False),
        sa.Column('rendered_storage_key', sa.Text(), nullable=False),
        sa.Column('width_px', sa.Integer(), nullable=False),
        sa.Column('height_px', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint('page_index >= 1', name='ck_report_page_index'),
        sa.CheckConstraint('source_page_index >= 1', name='ck_report_page_source_index'),
        sa.ForeignKeyConstraint(['source_asset_id', 'asset_set_id', 'user_id', 'subject_user_id'], ['health_report_assets.id', 'health_report_assets.asset_set_id', 'health_report_assets.user_id', 'health_report_assets.subject_user_id'], name='fk_report_page_asset_tenant', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['asset_set_id', 'user_id', 'subject_user_id'], ['health_report_asset_sets.id', 'health_report_asset_sets.user_id', 'health_report_asset_sets.subject_user_id'], name='fk_report_page_set_tenant', ondelete='CASCADE'),
        sa.UniqueConstraint('source_asset_id', 'user_id', 'subject_user_id', 'source_page_index', name='uq_report_page_asset_source_index'),
        sa.UniqueConstraint('asset_set_id', 'user_id', 'subject_user_id', 'page_index', name='uq_report_page_set_index'),
        sa.UniqueConstraint('id', 'asset_set_id', 'user_id', 'subject_user_id', name='uq_report_page_set_tenant_id'),
        sa.UniqueConstraint('id', 'user_id', 'subject_user_id', name='uq_report_page_tenant_id'),
    )
    op.create_index('ix_report_page_set_order', 'health_report_pages', ['user_id', 'subject_user_id', 'asset_set_id', 'page_index'], unique=False)
    op.create_table('health_report_completeness_assessments',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('asset_set_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('detector_id', sa.String(length=80), nullable=False),
        sa.Column('detector_version', sa.String(length=80), nullable=False),
        sa.Column('completeness_status', sa.String(length=24), nullable=False),
        sa.Column('basis', sa.String(length=32), nullable=False),
        sa.Column('expected_page_count', sa.Integer(), nullable=False),
        sa.Column('observed_page_count', sa.Integer(), nullable=False),
        sa.Column('missing_page_indices', JSONB, nullable=False, server_default=sa.text("'[]'")),
        sa.Column('evidence', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('failure_code', sa.String(length=80), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("basis IN ('user_declared', 'pdf_page_count', 'ocr_page_numbers', 'legacy')", name='ck_report_completeness_basis'),
        sa.CheckConstraint('expected_page_count >= 1', name='ck_report_completeness_expected'),
        sa.CheckConstraint('observed_page_count >= 0', name='ck_report_completeness_observed'),
        sa.CheckConstraint("completeness_status IN ('complete', 'missing_page', 'invalid_manifest')", name='ck_report_completeness_status'),
        sa.ForeignKeyConstraint(['asset_set_id', 'user_id', 'subject_user_id'], ['health_report_asset_sets.id', 'health_report_asset_sets.user_id', 'health_report_asset_sets.subject_user_id'], name='fk_report_completeness_set_tenant', ondelete='CASCADE'),
        sa.UniqueConstraint('asset_set_id', 'user_id', 'subject_user_id', 'detector_id', 'detector_version', name='uq_report_completeness_detector_version'),
    )
    op.create_table('health_report_asset_quality_results',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('page_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('detector_id', sa.String(length=80), nullable=False),
        sa.Column('detector_version', sa.String(length=80), nullable=False),
        sa.Column('quality_status', sa.String(length=24), nullable=False),
        sa.Column('blur_score', sa.Numeric(14, 4), nullable=True),
        sa.Column('quality_metrics', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('missing_page_evidence', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('failure_code', sa.String(length=80), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint('blur_score IS NULL OR blur_score >= 0', name='ck_report_asset_blur_score'),
        sa.CheckConstraint("quality_status IN ('accepted', 'blurry', 'blank', 'unreadable', 'low_resolution')", name='ck_report_asset_quality_status'),
        sa.ForeignKeyConstraint(['page_id', 'user_id', 'subject_user_id'], ['health_report_pages.id', 'health_report_pages.user_id', 'health_report_pages.subject_user_id'], name='fk_report_asset_quality_page_tenant', ondelete='CASCADE'),
        sa.UniqueConstraint('page_id', 'user_id', 'subject_user_id', 'detector_id', 'detector_version', name='uq_report_asset_quality_detector_version'),
    )
    op.create_table('health_report_field_locators',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('asset_set_id', sa.Integer(), nullable=False),
        sa.Column('page_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('x', sa.Numeric(7, 6), nullable=False),
        sa.Column('y', sa.Numeric(7, 6), nullable=False),
        sa.Column('width', sa.Numeric(7, 6), nullable=False),
        sa.Column('height', sa.Numeric(7, 6), nullable=False),
        sa.Column('region_index', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('region_role', sa.String(length=32), nullable=False, server_default='value'),
        sa.Column('polygon_norm', JSONB, nullable=False, server_default=sa.text("'[]'")),
        sa.Column('provider_id', sa.String(length=80), nullable=True),
        sa.Column('model_version', sa.String(length=80), nullable=True),
        sa.Column('confidence', sa.Numeric(5, 4), nullable=True),
        sa.Column('coordinate_space', sa.String(length=32), nullable=False, server_default='normalized_top_left'),
        sa.Column('locator_version', sa.String(length=80), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint('y + height <= 1', name='ck_report_field_locator_bottom'),
        sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_report_field_locator_confidence'),
        sa.CheckConstraint("coordinate_space = 'normalized_top_left'", name='ck_report_field_locator_coordinate_space'),
        sa.CheckConstraint('height > 0 AND height <= 1', name='ck_report_field_locator_height'),
        sa.CheckConstraint('region_index >= 1', name='ck_report_field_locator_region_index'),
        sa.CheckConstraint("region_role IN ('name', 'value', 'unit', 'reference', 'row')", name='ck_report_field_locator_region_role'),
        sa.CheckConstraint('x + width <= 1', name='ck_report_field_locator_right'),
        sa.CheckConstraint('width > 0 AND width <= 1', name='ck_report_field_locator_width'),
        sa.CheckConstraint('x >= 0 AND x <= 1', name='ck_report_field_locator_x'),
        sa.CheckConstraint('y >= 0 AND y <= 1', name='ck_report_field_locator_y'),
        sa.ForeignKeyConstraint(['candidate_id', 'workflow_id', 'user_id', 'subject_user_id'], ['health_report_field_candidates.id', 'health_report_field_candidates.workflow_id', 'health_report_field_candidates.user_id', 'health_report_field_candidates.subject_user_id'], name='fk_report_field_locator_candidate_tenant', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['page_id', 'user_id', 'subject_user_id'], ['health_report_pages.id', 'health_report_pages.user_id', 'health_report_pages.subject_user_id'], name='fk_report_field_locator_page_tenant', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['asset_set_id', 'workflow_id', 'user_id', 'subject_user_id'], ['health_report_asset_set_workflow_links.asset_set_id', 'health_report_asset_set_workflow_links.workflow_id', 'health_report_asset_set_workflow_links.user_id', 'health_report_asset_set_workflow_links.subject_user_id'], name='fk_report_field_locator_set_workflow_tenant', ondelete='CASCADE'),
        sa.UniqueConstraint('candidate_id', 'workflow_id', 'user_id', 'subject_user_id', 'region_index', name='uq_report_field_locator_candidate_region'),
    )
    op.create_table('health_report_descriptors',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('title', sa.String(length=256), nullable=False),
        sa.Column('hospital', sa.String(length=256), nullable=True),
        sa.Column('hospital_normalized', sa.String(length=256), nullable=True),
        sa.Column('report_date', sa.Date(), nullable=True),
        sa.Column('report_type', sa.String(length=24), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['workflow_id', 'user_id', 'subject_user_id'], ['health_report_workflows.id', 'health_report_workflows.user_id', 'health_report_workflows.subject_user_id'], name='fk_report_descriptor_workflow_tenant', ondelete='CASCADE'),
        sa.UniqueConstraint('workflow_id', 'user_id', 'subject_user_id', name='uq_report_descriptor_workflow'),
    )
    op.create_index('ix_report_descriptor_history', 'health_report_descriptors', ['user_id', 'subject_user_id', 'report_date', 'hospital_normalized', 'report_type'], unique=False)
    op.create_table('health_report_semantic_signatures',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('algorithm_version', sa.String(length=80), nullable=False),
        sa.Column('threshold_version', sa.String(length=80), nullable=False),
        sa.Column('report_type', sa.String(length=24), nullable=False),
        sa.Column('report_date_key', sa.String(length=16), nullable=True),
        sa.Column('hospital_key', sa.String(length=256), nullable=True),
        sa.Column('normalized_metadata', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('field_token_manifest', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('signature_hash', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['workflow_id', 'user_id', 'subject_user_id'], ['health_report_workflows.id', 'health_report_workflows.user_id', 'health_report_workflows.subject_user_id'], name='fk_report_semantic_signature_workflow_tenant', ondelete='CASCADE'),
        sa.UniqueConstraint('workflow_id', 'user_id', 'subject_user_id', 'algorithm_version', name='uq_report_semantic_signature_workflow_version'),
    )
    op.create_index('ix_report_semantic_signature_candidates', 'health_report_semantic_signatures', ['user_id', 'subject_user_id', 'report_type', 'report_date_key', 'hospital_key'], unique=False)
    op.create_table('health_report_exact_duplicate_matches',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('asset_set_id', sa.Integer(), nullable=False),
        sa.Column('matched_workflow_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('aggregate_sha256', sa.String(length=64), nullable=False),
        sa.Column('matched_document_fingerprint', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint('length(aggregate_sha256) = 64', name='ck_report_exact_duplicate_digest'),
        sa.ForeignKeyConstraint(['asset_set_id', 'user_id', 'subject_user_id'], ['health_report_asset_sets.id', 'health_report_asset_sets.user_id', 'health_report_asset_sets.subject_user_id'], name='fk_report_exact_duplicate_set_tenant', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['matched_workflow_id', 'user_id', 'subject_user_id'], ['health_report_workflows.id', 'health_report_workflows.user_id', 'health_report_workflows.subject_user_id'], name='fk_report_exact_duplicate_workflow_tenant', ondelete='RESTRICT'),
        sa.UniqueConstraint('asset_set_id', 'user_id', 'subject_user_id', name='uq_report_exact_duplicate_set'),
    )
    op.create_table('health_report_duplicate_decisions',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('matched_workflow_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('duplicate_kind', sa.String(length=16), nullable=False),
        sa.Column('semantic_algorithm_version', sa.String(length=80), nullable=False),
        sa.Column('similarity', sa.Numeric(5, 4), nullable=False),
        sa.Column('decision_status', sa.String(length=32), nullable=False, server_default='awaiting_user_choice'),
        sa.Column('detection_key', sa.String(length=96), nullable=False),
        sa.Column('decision_client_event_id', sa.String(length=80), nullable=True),
        sa.Column('evidence', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('decided_by_user_id', sa.BigInteger(), nullable=True),
        sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("(decision_status = 'awaiting_user_choice' AND decided_by_user_id IS NULL AND decided_at IS NULL AND decision_client_event_id IS NULL) OR (decision_status <> 'awaiting_user_choice' AND decided_by_user_id IS NOT NULL AND decided_at IS NOT NULL AND decision_client_event_id IS NOT NULL)", name='ck_report_duplicate_decision_complete'),
        sa.CheckConstraint("decision_status IN ('awaiting_user_choice', 'use_existing', 'continue_new')", name='ck_report_duplicate_decision_status'),
        sa.CheckConstraint('workflow_id <> matched_workflow_id', name='ck_report_duplicate_distinct_workflows'),
        sa.CheckConstraint("duplicate_kind IN ('semantic')", name='ck_report_duplicate_kind'),
        sa.CheckConstraint('similarity >= 0 AND similarity <= 1', name='ck_report_duplicate_similarity'),
        sa.ForeignKeyConstraint(['decided_by_user_id'], ['user_account.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['matched_workflow_id', 'user_id', 'subject_user_id'], ['health_report_workflows.id', 'health_report_workflows.user_id', 'health_report_workflows.subject_user_id'], name='fk_report_duplicate_match_tenant', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['workflow_id', 'user_id', 'subject_user_id'], ['health_report_workflows.id', 'health_report_workflows.user_id', 'health_report_workflows.subject_user_id'], name='fk_report_duplicate_workflow_tenant', ondelete='CASCADE'),
        sa.UniqueConstraint('user_id', 'subject_user_id', 'decision_client_event_id', name='uq_report_duplicate_decision_tenant_event'),
        sa.UniqueConstraint('id', 'user_id', 'subject_user_id', name='uq_report_duplicate_decision_tenant_id'),
        sa.UniqueConstraint('user_id', 'subject_user_id', 'detection_key', name='uq_report_duplicate_detection_key'),
        sa.UniqueConstraint('workflow_id', 'matched_workflow_id', 'user_id', 'subject_user_id', 'semantic_algorithm_version', name='uq_report_duplicate_pair_version'),
        sa.UniqueConstraint('workflow_id', 'user_id', 'subject_user_id', 'semantic_algorithm_version', name='uq_report_duplicate_top_match_version'),
    )
    op.create_index('ix_report_duplicate_pending', 'health_report_duplicate_decisions', ['user_id', 'subject_user_id', 'decision_status', 'created_at'], unique=False)
    op.create_table('health_report_score_jobs',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('job_key', sa.String(length=96), nullable=False),
        sa.Column('input_revision', sa.Integer(), nullable=False),
        sa.Column('algorithm_bundle_version', sa.String(length=80), nullable=False),
        sa.Column('input_manifest_digest', sa.String(length=64), nullable=False),
        sa.Column('evidence_cutoff_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('supersedes_job_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=24), nullable=False, server_default='pending'),
        sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('max_attempts', sa.Integer(), nullable=False, server_default='3'),
        sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('lease_token', sa.String(length=96), nullable=True),
        sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_failure_code', sa.String(length=80), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint('attempt_count <= max_attempts', name='ck_report_score_job_attempt_bound'),
        sa.CheckConstraint('attempt_count >= 0', name='ck_report_score_job_attempts'),
        sa.CheckConstraint('(lease_token IS NULL AND lease_expires_at IS NULL) OR (lease_token IS NOT NULL AND lease_expires_at IS NOT NULL)', name='ck_report_score_job_lease_pair'),
        sa.CheckConstraint('max_attempts >= 1', name='ck_report_score_job_max_attempts'),
        sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'partial_failed', 'failed', 'cancelled')", name='ck_report_score_job_status'),
        sa.ForeignKeyConstraint(['supersedes_job_id', 'workflow_id', 'user_id', 'subject_user_id'], ['health_report_score_jobs.id', 'health_report_score_jobs.workflow_id', 'health_report_score_jobs.user_id', 'health_report_score_jobs.subject_user_id'], name='fk_report_score_job_supersedes_tenant', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['workflow_id', 'user_id', 'subject_user_id'], ['health_report_workflows.id', 'health_report_workflows.user_id', 'health_report_workflows.subject_user_id'], name='fk_report_score_job_workflow_tenant', ondelete='RESTRICT'),
        sa.UniqueConstraint('id', 'user_id', 'subject_user_id', name='uq_report_score_job_tenant_id'),
        sa.UniqueConstraint('user_id', 'subject_user_id', 'job_key', name='uq_report_score_job_tenant_key'),
        sa.UniqueConstraint('workflow_id', 'user_id', 'subject_user_id', 'algorithm_bundle_version', 'input_revision', name='uq_report_score_job_workflow_bundle_revision'),
        sa.UniqueConstraint('id', 'workflow_id', 'user_id', 'subject_user_id', name='uq_report_score_job_workflow_tenant_id'),
    )
    op.create_index('ix_report_score_job_claim', 'health_report_score_jobs', ['status', 'next_attempt_at', 'lease_expires_at', 'id'], unique=False)
    op.create_table('health_report_score_job_items',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('job_id', sa.Integer(), nullable=False),
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('score_kind', sa.String(length=24), nullable=False),
        sa.Column('policy_id', sa.String(length=80), nullable=False),
        sa.Column('policy_version', sa.String(length=80), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False, server_default='pending'),
        sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('input_manifest', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('missing_inputs', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('failure_code', sa.String(length=80), nullable=True),
        sa.Column('retryable', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('failure_message_key', sa.String(length=128), nullable=True),
        sa.Column('failure_message_params', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('method_summary_key', sa.String(length=128), nullable=False),
        sa.Column('method_summary_params', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('catalog_version', sa.String(length=80), nullable=False),
        sa.Column('input_basis', JSONB, nullable=False, server_default=sa.text("'[]'")),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint('attempt_count >= 0', name='ck_report_score_job_item_attempts'),
        sa.CheckConstraint("score_kind IN ('stress', 'recovery', 'inflammation')", name='ck_report_score_job_item_kind'),
        sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'unavailable', 'failed', 'cancelled')", name='ck_report_score_job_item_status'),
        sa.ForeignKeyConstraint(['job_id', 'workflow_id', 'user_id', 'subject_user_id'], ['health_report_score_jobs.id', 'health_report_score_jobs.workflow_id', 'health_report_score_jobs.user_id', 'health_report_score_jobs.subject_user_id'], name='fk_report_score_job_item_job_tenant', ondelete='CASCADE'),
        sa.UniqueConstraint('job_id', 'user_id', 'subject_user_id', 'score_kind', name='uq_report_score_job_item_kind'),
        sa.UniqueConstraint('id', 'user_id', 'subject_user_id', name='uq_report_score_job_item_tenant_id'),
        sa.UniqueConstraint('id', 'workflow_id', 'user_id', 'subject_user_id', name='uq_report_score_job_item_workflow_tenant_id'),
    )
    op.create_table('health_report_score_snapshot_links',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('job_item_id', sa.Integer(), nullable=False),
        sa.Column('snapshot_id', sa.Integer(), nullable=False),
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['job_item_id', 'workflow_id', 'user_id', 'subject_user_id'], ['health_report_score_job_items.id', 'health_report_score_job_items.workflow_id', 'health_report_score_job_items.user_id', 'health_report_score_job_items.subject_user_id'], name='fk_report_score_snapshot_link_item_tenant', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['snapshot_id', 'workflow_id', 'user_id', 'subject_user_id'], ['health_score_snapshots.id', 'health_score_snapshots.source_report_workflow_id', 'health_score_snapshots.user_id', 'health_score_snapshots.subject_user_id'], name='fk_report_score_snapshot_link_snapshot_tenant', ondelete='RESTRICT'),
        sa.UniqueConstraint('job_item_id', 'user_id', 'subject_user_id', name='uq_report_score_snapshot_link_item'),
        sa.UniqueConstraint('snapshot_id', 'workflow_id', 'user_id', 'subject_user_id', name='uq_report_score_snapshot_link_snapshot'),
    )
    op.create_table('health_report_follow_up_items',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('rule_id', sa.String(length=80), nullable=False),
        sa.Column('rule_version', sa.String(length=80), nullable=False),
        sa.Column('item_code', sa.String(length=80), nullable=False),
        sa.Column('message_key', sa.String(length=128), nullable=False),
        sa.Column('message_params', JSONB, nullable=False, server_default=sa.text("'{}'")),
        sa.Column('status', sa.String(length=16), nullable=False, server_default='active'),
        sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("status IN ('active', 'resolved', 'retracted')", name='ck_report_follow_up_status'),
        sa.ForeignKeyConstraint(['workflow_id', 'user_id', 'subject_user_id'], ['health_report_workflows.id', 'health_report_workflows.user_id', 'health_report_workflows.subject_user_id'], name='fk_report_follow_up_workflow_tenant', ondelete='CASCADE'),
        sa.UniqueConstraint('id', 'workflow_id', 'user_id', 'subject_user_id', name='uq_report_follow_up_item_workflow_tenant_id'),
        sa.UniqueConstraint('workflow_id', 'user_id', 'subject_user_id', 'rule_id', 'rule_version', 'item_code', name='uq_report_follow_up_rule_source'),
    )
    op.create_index('ix_report_follow_up_active', 'health_report_follow_up_items', ['user_id', 'subject_user_id', 'workflow_id', 'status'], unique=False)
    op.create_table('health_report_follow_up_evidence',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('follow_up_item_id', sa.Integer(), nullable=False),
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
        sa.Column('evidence_key', sa.String(length=96), nullable=False),
        sa.Column('source_kind', sa.String(length=32), nullable=False),
        sa.Column('observation_id', sa.Integer(), nullable=True),
        sa.Column('confirmation_event_id', sa.Integer(), nullable=True),
        sa.Column('confirmation_candidate_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("(source_kind = 'confirmed_observation' AND observation_id IS NOT NULL AND confirmation_event_id IS NULL AND confirmation_candidate_id IS NULL) OR (source_kind = 'clinician_confirmation' AND observation_id IS NULL AND confirmation_event_id IS NOT NULL AND confirmation_candidate_id IS NOT NULL)", name='ck_report_follow_up_evidence_source_complete'),
        sa.CheckConstraint("source_kind IN ('confirmed_observation', 'clinician_confirmation')", name='ck_report_follow_up_evidence_source_kind'),
        sa.ForeignKeyConstraint(['confirmation_event_id', 'confirmation_candidate_id', 'workflow_id', 'user_id', 'subject_user_id'], ['health_report_confirmation_events.id', 'health_report_confirmation_events.candidate_id', 'health_report_confirmation_events.workflow_id', 'health_report_confirmation_events.user_id', 'health_report_confirmation_events.subject_user_id'], name='fk_report_follow_up_evidence_confirmation_tenant', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['follow_up_item_id', 'workflow_id', 'user_id', 'subject_user_id'], ['health_report_follow_up_items.id', 'health_report_follow_up_items.workflow_id', 'health_report_follow_up_items.user_id', 'health_report_follow_up_items.subject_user_id'], name='fk_report_follow_up_evidence_item_tenant', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['observation_id', 'user_id', 'subject_user_id'], ['confirmed_health_observations.id', 'confirmed_health_observations.user_id', 'confirmed_health_observations.subject_user_id'], name='fk_report_follow_up_evidence_observation_tenant', ondelete='RESTRICT'),
        sa.UniqueConstraint('follow_up_item_id', 'workflow_id', 'user_id', 'subject_user_id', 'evidence_key', name='uq_report_follow_up_evidence_key'),
    )


def downgrade() -> None:
    op.drop_table("health_report_follow_up_evidence")
    op.drop_table("health_report_follow_up_items")
    op.drop_table("health_report_score_snapshot_links")
    op.drop_table("health_report_score_job_items")
    op.drop_table("health_report_score_jobs")
    op.drop_table("health_report_duplicate_decisions")
    op.drop_table("health_report_exact_duplicate_matches")
    op.drop_table("health_report_semantic_signatures")
    op.drop_table("health_report_descriptors")
    op.drop_table("health_report_field_locators")
    op.drop_table("health_report_asset_quality_results")
    op.drop_table("health_report_completeness_assessments")
    op.drop_table("health_report_pages")
    op.drop_table("health_report_asset_set_workflow_links")
    op.drop_table("health_report_assets")
    op.drop_table("health_report_asset_sets")
    op.drop_table("health_profile_goal_revisions")
    op.drop_table("health_profile_goal_metrics")
    op.drop_table("health_profile_goals")
    op.drop_table("health_profile_device_source_links")
    op.drop_table("health_profile_fact_source_versions")
    op.drop_table("trusted_device_profile_observations")
    op.drop_index("ix_profile_revision_candidate_history", table_name="health_profile_revisions")
    op.drop_index("ix_profile_revision_fact_history", table_name="health_profile_revisions")
    op.drop_constraint("uq_score_snapshot_workflow_tenant_id", "health_score_snapshots", type_="unique")
    op.drop_constraint("uq_profile_source_tenant_id", "health_profile_sources", type_="unique")
    op.drop_constraint("uq_user_indicator_value_id_user", "user_indicator_values", type_="unique")
    op.drop_column("trusted_medication_plans", "purpose")
